import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import bgImage from '@/public/bgImage.jpg'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className='relative min-h-screen text-white'>
        <div className="fixed inset-0 -z-10 overflow-hidden">
          <Image
            src = {bgImage}
            alt='Site background'
            placeholder='blur'
            priority
            fill
            quality={100}
            className='object-cover'
           />
        </div>
        <div className='relative z-10'>
          {children}
        </div>
      </body>
    </html>
  );
}
